### ISSUE TITLE
You should make  the cotainer_name alfer `-i` when you run `docker exec `

### ISSUE THREAD

**Issue by ghost** [treadie/docker-arachni#2]
### like this 
`docker exec -i arachni  /opt/arachni/bin/arachni_web_task db:setup`

## docker-compose.yml 
```
version: '2'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=arachni
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=arachni_production
    volumes:
      - /var/lib/arachni_pgsqldata:/var/lib/postgresql/data

  arachni:
    image: treadie/arachni
    links:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime

    ports:
      - 9292:9292
```

## Quick Start 

1、`docker-compose up -d`

2、`docker exec -i ********_arachni_1 /opt/arachni/bin/arachni_web_task db:setup`
